server:
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false